### PR TITLE
Moves signal metadata to tooltip

### PR DESCRIPTION
**Pull request by bboettcher3**
Clean and simple :)
- Tested with signals of varying length, units, instances
- Some fields only show up if set (instances, unit)
- Can add other fields later to display (description would be useful)

image

### CODE REVIEW

**Comment by bboettcher3** [comment]
Copying comment from @malloch on the IDMIL's Slack:
"I'm wondering whether a user should be able to toggle between simple<->detailed versions of the list view. Some users might want to know the datatype/vector length/unit/numInstances without needing to hover over each signal. In the old Max GUI we used columns for metadata and could sort by e.g. vector length."

For myself, I still think that a simpler signal display is better for readability, but maybe to compromise: just keep the signal length in the simple view with the signal name? All other fields to me seem useful when customizing the connection but not too useful before then. Any thoughts @DocSunset as well?

**Comment by DocSunset** [comment]
I think "The Right Thing"™️would be to allow the user to toggle what metadata is included in the list view display. That said, I also prefer the uncluttered simple view, so I would be in favor of merging this as is for now and implementing detail customization at a later time.

**Comment by malloch** [comment]
@DocSunset since you have done research on _how_ people make mapping decisions, do you have any findings that could help us here? Personally I want to know the datatype, vector length, and whether a signal is instanced _before_ creating a map, and I need to know the units or at least the range when writing an expression. For me mousing over each signal to discover these data seems annoying. Are others thinking that the signal name alone is sufficient for choosing which signals to map?

**Comment by DocSunset** [comment]
In the context of my thesis, all the signals were normalized single floats, so I don't think the observations generalize well to the contexts at play here.

That said, most participants (roughly speaking from memory) 1) had a learning period where they spent time getting acquainted with the signals available to them and 2) used mostly the default linear mapping expression.

I think it's interesting @malloch that we have opposite preferences. I feel like after a certain amount of experience with a device (e.g. the T-Stick), I have learned most or all of its metadata and don't want to have to see it in the display all the time when I'm really just scanning signal names looking for the specific one I want.

That makes me consider, what is the problem that this PR solves? Why might it be considered preferable to have tooltips? Are there alternative solutions to the problem being solved that also address Joe's preference?

**Comment by bboettcher3** [comment]
I guess the intent was to make a more readable and scalable place to view signal metadata instead of being forced to compress everything into 1 or 2 lines. I don't have anything against having both the detailed version + the tooltips, but we should only keep necessary fields in the signal area.

A proposal for fields in the signal area:
Name, length, units (if present), instanced (only visible if instanced)

I left out the data type as I don't think a signal being an int or float will mean much to the average (nontechnical) user or would influence choosing mappings.
Thoughts?

**Comment by bboettcher3** [comment]
Added back the signal length, I think this looks good!
image

Compared to the existing:
image

**Comment by malloch** [comment]
@bboettcher3 What about when a map is selected and the user is editing the expression. As I understand it they would have to mouseover the source and destination signals in order to discover the signal ranges – is this correct?

**Comment by bboettcher3** [comment]
Yep, that's correct. Although, the default expression already displays the min and max, so maybe they wouldn't even have to look.

**Pull request merged**
